services:
  app-dm-water-consumption:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-water-consumption
    volumes:
      - .:/dm-water-consumption
    env_file:
      - /.env
    environment:
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    ports:
      - "8400:8400"
    depends_on:
      db-dm-water-consumption:
        condition: service_healthy

  db-dm-water-consumption:
    container_name: db-water-consumption
    image: postgres:15
    volumes:
      - ./data/db-dm-water-consumption:/var/lib/postgresql/data
    env_file:
      - /.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 30s
      retries: 6
