version: '3.9'

services:
  dm-water-consumption:
    networks:
      - dm-water-consumption
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: bash -c "poetry run python src/main.py"
    container_name: dm-water-consumption
    volumes:
      - .:/dm-water-consumption
    ports:
      - "8400:8400"



networks:
  dm-water-consumption:
